variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql
  PLUGIN_SLUG: alpine-photo-tile-for-instagram
  PLUGIN_VERSION: 1.2.8

cache:
  paths:
    - $HOME/.composer
    - /root/.composer

stages:
  - test
  - package
  - deploy

before_script:
  # Set up WordPress tests
  - bash bin/install-wp-tests.sh $MYSQL_DATABASE root $MYSQL_ROOT_PASSWORD mysql latest true

  # PHPUnit
  - |
    if [[ $(php -v) =~ "PHP 7." ]]; then
      composer global require "phpunit/phpunit=6.1.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi

  # Install PHPCS and WPCS
  - composer global require automattic/vipwpcs
  - composer global require phpcompatibility/phpcompatibility-wp
  - phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/automattic/vipwpcs,$HOME/.composer/vendor/phpcompatibility/php-compatibility,$HOME/.composer/vendor/phpcompatibility/phpcompatibility-paragonie,$HOME/.composer/vendor/phpcompatibility/phpcompatibility-wp

PHPunit:PHP5.6:MySQL5.6:
  stage: test
  image: containers.ethitter.com:443/docker/images/php:5.6
  services:
    - mysql:5.6
  script:
    - find . -type "f" -iname "*.php" | xargs -L "1" php -l
 #   - phpcs -n
    - phpunit
  artifacts:
    reports:
      junit: phpunit-testresults.xml
  only:
    - master

PHPunit:PHP7.1:MySQL5.6:
  stage: test
  image: containers.ethitter.com:443/docker/images/php:7.1
  services:
    - mysql:5.6
  script:
    - find . -type "f" -iname "*.php" | xargs -L "1" php -l
 #   - phpcs -n
    - phpunit
  artifacts:
    reports:
      junit: phpunit-testresults.xml
  only:
    - master

PHPunit:PHP7.2:MySQL5.6:
  stage: test
  image: containers.ethitter.com:443/docker/images/php:7.2
  services:
    - mysql:5.6
  script:
    - find . -type "f" -iname "*.php" | xargs -L "1" php -l
 #   - phpcs -n
    - phpunit
  artifacts:
    reports:
      junit: phpunit-testresults.xml
  only:
    - master

PHPunit:PHP7.3:MySQL5.6:
  stage: test
  image: containers.ethitter.com:443/docker/images/php:7.3
  services:
    - mysql:5.6
  script:
    - find . -type "f" -iname "*.php" | xargs -L "1" php -l
 #   - phpcs -n
    - phpunit
  artifacts:
    reports:
      junit: phpunit-testresults.xml

JS:Node10:Jest:
  stage: test
  image: node:10.15.3
  before_script: []
  cache:
    paths:
      - node_modules
  script:
    - npm install
    - npm test
  artifacts:
    reports:
      junit: test-report.xml

CreatePluginZIP:
  stage: package
  image: alpine:latest
  before_script: []
  script:
    - apk update
    - apk add zip
    - zip -r alpine_phototile_for_instagram.zip css/** gears/** js/** cache/** alpine-phototile-for-instagram.php README.md LICENSE ABOUT.md
  artifacts:
    paths:
      - alpine_phototile_for_instagram.zip

ReleaseWPPlugin:
  stage: deploy
  image: containers.ethitter.com:443/docker/images/php:7.3
  before_script:
    - curl -o ./bin/deploy.sh https://git-cdn.e15r.co/open-source/wp-org-plugin-deploy/raw/master/scripts/deploy.sh
    - chmod +x ./bin/deploy.sh
  script: ./bin/deploy.sh
  when: manual
  only:
    - master
